<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Java异常：Throwable - 菜鸟程序员博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="Java异常：Throwable" />
<meta property="og:description" content="一、概述
1、Throwable接口 1）Error 类 2）Exception 类 编译期问题： 不是 RuntimeException 的异常必须进行处理的，因为你不处理，编译就不能通过。运行期问题： RuntimeException 异常这种问题我们也不处理，因为是你的问题，而且这个问题出现肯定是我们的代码不够严谨，需要修正代码的。 二、异常的处理： （一）异常的处理方式 1、JVM的默认处理：报错。 把异常的名称，原因，位置等信息输出在控制台，程序不能继续执行了。 2、自己处理 1）方式1： try...catch...finally ：自己编写处理代码，后面的程序可以继续执行 。spring事务中不可以继续执行，其默认只要是RuntimeException ,都会回滚。 2）方式2： throws ：把自己处理不了的，在方法上声明，告诉调用者，这里有问题。 3、面试题：编译期异常和运行期异常的区别? 编译期异常： 必须要处理的，否则编译不通过 运行期异常： 可以不处理，也可以处理 （二）处理详解 1、try...catch...finally 处理（实例） &lt;span style=&#34;font-size:18px;&#34;&gt;&lt;span style=&#34;font-family:Arial;&#34;&gt;	/* * 多个异常 * b:写一个try，多个catch * try{ * ... * }catch(异常类名 变量名) { * ... * } * catch(异常类名 变量名) { * ... * } * ... * * 注意事项： * 1:能明确的尽量明确，不要用大的来处理。 * 2:平级关系的异常谁前谁后无所谓，如果出现了子父关系，父必须在后面。 * * 注意： * 一旦try里面出了问题，就会在这里把问题给抛出去，然后和catch里面的问题进行匹配， * 一旦有匹配的，就执行catch里面的处理，然后结束了try." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://cainiaoprogram.github.io/posts/a5fb8a85bfc1bb7b1b7171e6700fffe0/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2022-05-31T21:58:01+08:00" />
<meta property="article:modified_time" content="2022-05-31T21:58:01+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="菜鸟程序员博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">菜鸟程序员博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">Java异常：Throwable</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p><strong>一、<span style="background-color:inherit;">概述</span></strong></p> 
<div>
  1、Throwable接口 
</div> 
<div>
  1）Error 类 
</div> 
<div>
  2）Exception 类 
</div> 
<div> 
 <ul><li>编译期问题： 
   <ul><li>不是 RuntimeException 的异常</li><li>必须进行处理的，因为你不处理，编译就不能通过。</li></ul></li><li>运行期问题： 
   <ul><li>RuntimeException 异常</li><li>这种问题我们也不处理，因为是你的问题，而且这个问题出现肯定是我们的代码不够严谨，需要修正代码的。</li></ul></li></ul> 
</div> 
<p></p> 
<p><strong>二、<span style="background-color:inherit;">异常的处理： </span></strong></p> 
<div>
  （一）异常的处理方式 
</div> 
<div>
  1、JVM的默认处理：报错。 
</div> 
<div>
  把异常的名称，原因，位置等信息输出在控制台，程序不能继续执行了。 
</div> 
<div></div> 
<div>
  2、自己处理 
</div> 
<div>
  1）方式1： 
</div> 
<div> 
 <ul><li>try...catch...finally ：自己编写处理代码，<span style="background-color:#599ffe;">后面的程序可以继续执行 。</span></li><li><span style="background-color:#599ffe;">spring事务中不可以继续执行，其默认只要是RuntimeException ,都会回滚。</span></li></ul> 
</div> 
<div>
  2）方式2： 
</div> 
<div> 
 <ul><li>throws ：把自己处理不了的，在方法上声明，告诉调用者，这里有问题。</li></ul> 
</div> 
<div> 
 <div>
   3、面试题：编译期异常和运行期异常的区别?  
 </div> 
 <div> 
  <ul><li>编译期异常： 必须要处理的，否则编译不通过 </li><li>运行期异常： 可以不处理，也可以处理</li></ul> 
  <div> 
   <div>
     （二）处理详解 
   </div> 
   <div>
     1、try...catch...finally 处理（实例） 
   </div> 
   <div> 
    <pre class="has"><code class="language-java">&lt;span style="font-size:18px;"&gt;&lt;span style="font-family:Arial;"&gt;	/*
	 * 多个异常
	 * 		b:写一个try，多个catch
	 * 			try{
	 * 				...
	 * 			}catch(异常类名 变量名) {
	 * 				...
	 * 			}
	 * 			catch(异常类名 变量名) {
	 * 				...
	 * 			}
	 * 			...
	 * 
	 * 			注意事项：
	 * 				1:能明确的尽量明确，不要用大的来处理。
	 * 				2:平级关系的异常谁前谁后无所谓，如果出现了子父关系，父必须在后面。
	 * 
	 * 注意：
	 * 		一旦try里面出了问题，就会在这里把问题给抛出去，然后和catch里面的问题进行匹配，
	 * 		一旦有匹配的，就执行catch里面的处理，然后结束了try...catch
	 * 		继续执行后面的语句。
	 */
	public void test3(){
		
		int a = 10;
		int b = 0;
		int[] arr = { 1, 2, 3 };

		// 爷爷一定要在最后
		try {
			System.out.println(a / b);
			System.out.println(arr[3]);
			System.out.println("这里出现了一个异常，你不太清楚是谁，该怎么办呢?");
		} catch (ArithmeticException e) {//兄弟，有异常就不会去另外的catch 了
			System.out.println("除数不能为0");
		} catch (ArrayIndexOutOfBoundsException e) {//兄弟
			System.out.println("你访问了不该的访问的索引");
		} catch (Exception e) {//爷爷一定要在后面
			System.out.println("出问题了");
		}

		System.out.println("over");//继续执行
	}
&lt;/span&gt;&lt;/span&gt;</code></pre> 
   </div> 
   <div> 
    <div>
      2、JDK7的新的异常 
    </div> 
    <div>
      1）格式：try{   }catch(异常名1 | 异常名2 | ... 变量 ) {  } 
    </div> 
    <div>
      2）注意 
    </div> 
    <div> 
     <ul><li>处理方式是一致的。(实际开发中，好多时候可能就是针对同类型的问题，给出同一个处理) </li><li>多个异常间必须是平级关系，父类异常没有办法处理。</li></ul> 
    </div> 
   </div> 
   <div> 
    <div>
      3、异常常用方法 
    </div> 
    <div>
      1）public String getMessage()：异常的消息字符串 
    </div> 
    <div>
      2）public String toString()：返回异常的简单信息描述 
    </div> 
    <div> 
     <ul><li>此对象的类的 name(全路径名) ": "（冒号和一个空格）  </li><li>调用此对象 getLocalizedMessage()方法的结果 (默认返回的是getMessage()的内容) </li></ul> 3）printStackTrace()： 获取异常类名和异常信息，以及异常出现在程序中的位置。返回值void。把信息输出在控制台。  
    </div> 
    <div></div> 
   </div> 
   <div> 
    <div>
      4、throws 抛出（在方法的定义上） 
    </div> 
    <div>
      1）格式： throws 异常类名，可以一次抛出多个  
    </div> 
    <div> 
     <ul><li>这个格式必须跟在方法的括号后面。 </li><li>public void test7() throws ArithmeticException {}</li></ul> 
     <div>
       2）注意： 
     </div> 
     <div> 
      <ul><li>调用该方法的方法，需要处理该异常，如不处理，继续抛出。</li></ul> 
     </div> 
    </div> 
    <div>
      3）小结： 
    </div> 
    <div> 
     <ul><li>编译期异常抛出，将来调用者必须处理。 </li><li>运行期异常抛出，将来调用可以不用处理。 </li></ul> 
    </div> 
    <div>
      5、throw（在方法体内） 
    </div> 
    <div>
      1）格式：throw 异常对象 
    </div> 
    <div> 
     <ul><li>如果出现了异常情况，我们可以把该异常抛出，这个时候的抛出的应该是异常的对象。</li><li>throw new ArithmeticException();</li><li>一般用于自定义的异常使用</li></ul> 
    </div> 
    <div>
      2）面试题：throw和throws是的区别 
    </div> 
    <div> 
     <ul><li>throw： 
       <ul><li>在方法体中，后面跟的是异常对象名，并且只能是一个。</li><li>抛出的是一个异常对象，说明这里肯定有一个异常产生了。</li></ul></li><li>throws： 
       <ul><li>在方法声明上，后面跟的是异常的类名，可以是多个。</li><li>是声明方法有异常，是一种可能性，这个异常并不一定会产生。</li></ul></li></ul> 
    </div> 
    <div>
      （三）finally关键字及其面试题 
    </div> 
    <div>
      1、finally用于释放资源，它的代码永远会执行。特殊情况：在执行到finally之前jvm退出了 
    </div> 
    <div>
      2、面试题 
    </div> 
    <div> 
     <ul><li>final,finally,finalize的区别？ 
       <ul><li>final：最终的意思，可以修饰类，成员变量，成员方法 
         <ul><li>修饰类，类不能被继承 </li><li>修饰变量，变量是常量</li><li>修饰方法，方法不能被重写</li></ul></li><li>finally：是异常处理的一部分，用于释放资源。 
         <ul><li>一般来说，代码肯定会执行，特殊情况：在执行到finally之前jvm退出了</li></ul></li><li>finalize：是Object类的一个方法，用于垃圾回收。</li></ul></li></ul> 
     <ul><li>如果在catch里面有return,请问finally还执行吗?如果执行,在return前还是后 
       <ul><li>会执行，在 return 前面执行。</li><li>注意：返回路径就形成问题。*</li></ul></li></ul> 
    </div> 
    <pre class="has"><code class="language-java">&lt;span style="font-size:18px;"&gt;&lt;span style="font-family:Arial;"&gt;	/*
	 * 面试题：
	 * 1:final,finally和finalize的区别
	 * final：最终的意思，可以修饰类，成员变量，成员方法
	 * 		修饰类，类不能被继承
	 * 		修饰变量，变量是常量
	 * 		修饰方法，方法不能被重写
	 * finally：是异常处理的一部分，用于释放资源。
	 * 		一般来说，代码肯定会执行，特殊情况：在执行到finally之前jvm退出了
	 * finalize：是Object类的一个方法，用于垃圾回收
	 * 
	 * 2:如果catch里面有return语句，请问finally里面的代码还会执行吗?
	 *   如果会，请问是在return前，还是return后。
	 * 	   会。前。
	 * 
	 * 	 准确的说，应该是在中间。
	 * 
	 * 3:try...catch...finally的格式变形
	 * 		A:try...catch...finally
	 * 		B:try...catch
	 * 		C:try...catch...catch...
	 * 		D:try...catch...catch...finally
	 * 		E:try...finally
	 * 			这种做法的目前是为了释放资源。
	 */
	public int test10(){
		int a = 10;
		try {
			System.out.println(a / 0);
			a = 20;
		} catch (ArithmeticException e) {
			a = 30;
			return a;
			/*
			 * return a在程序执行到这一步的时候，这里不是return a而是return 30;这个返回路径就形成了。
			 * 但是呢，它发现后面还有finally，所以继续执行finally的内容，a=40
			 * 再次回到以前的返回路径，继续走return 30;
			 */
		} finally {
			a = 40;
			return a;//如果这样结果就是40了。
		}
//		 return a;
	}
&lt;/span&gt;&lt;/span&gt;</code></pre> 
    <br>   
   </div> 
   <div> 
    <div>
      （四）自定义异常： 
    </div> 
    <div>
      1）继承自Exception或者RuntimeException，只需要提供无参构造和一个带参构造即可。 
    </div> 
    <div>
      2）实例： 
    </div> 
    <div></div> 
    <div>
      6、异常的注意实现 
    </div> 
    <div>
      1）父的方法有异常抛出,子的重写方法在抛出异常的时候必须要小于等于父的异常 
    </div> 
    <div>
      2）父的方法没有异常抛出,子的重写方法不能有异常抛出 
    </div> 
    <div>
      3）父的方法抛出多个异常,子的重写方法必须比父少或者小 
    </div> 
    <div></div> 
    <pre class="has"><code class="language-java">&lt;span style="font-size:18px;"&gt;&lt;span style="font-family:Arial;"&gt;/*
 * java不可能对所有的情况都考虑到，所以，在实际的开发中，我们可能需要自己定义异常。
 * 而我们自己随意的写一个类，是不能作为异常类来看的，要想你的类是一个异常类，就必须继承自Exception或者RuntimeException
 * 只需要提供无参构造和一个带参构造即可。
 * 
 * 两种方式：
 * A:继承Exception，在throw的时候，需要处理
 * B:继承RuntimeException，运行期异常，在throw的时候，需要处理
 */
//public class MyException extends Exception {
	public class MyException extends RuntimeException {
	
	//只需要提供无参构造和一个带参构造即可。
	public MyException() {
	}

	public MyException(String message) {
		super(message);
	}
}&lt;/span&gt;&lt;/span&gt;</code></pre> 
   </div> 
   <div> 
    <div> 
     <span style="background-color:inherit;"><strong>三、Spring事务</strong></span> 
    </div> 
    <div>
      （一）事务 
    </div> 
    <div>
      1、传播行为：propagation=Propagation.REQUIRED  
    </div> 
    <div>
      2、隔离机制：isolation=Isolation.DEFAULT  
    </div> 
    <div>
      1）只读属性 ：readOnly 
    </div> 
    <div>
      2）回滚机制： 
    </div> 
    <div> 
     <ul><li>rollbackFor</li><li>noRollbackFor</li></ul> 
    </div> 
    <div>
      （二）面试 
    </div> 
    <div>
      1、回滚机制。 
    </div> 
    <div>
      1）try catch..无效，因为spring 的回滚机制为只要是运行期异常就会滚。 
    </div> 
    <div>
      2）解决：只要修改其回滚机制即可。 
    </div> 
   </div> 
   <div> 
    <img alt="" src="https://images2.imgbox.com/2c/77/baCuJ28A_o.png"> 
   </div> 
   <div></div> 
   <div></div> 
   <div>
     2）这个面试题，经常被问到（苏州）。 
    <span style="background-color:inherit;">我被面到的公司有：苏州中集、苏州科达（监控）、盟拓等。</span> 
   </div> 
   <div></div> 
   <div></div> 
   <div></div> 
  </div> 
 </div> 
</div> 
<p></p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/39d32695889c9613a6178a6bbd38c678/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">集合详解（四）：Map</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/b64a9f4f9e4cd6f595bdf4e9d5b38e68/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">TCP/IP协议抓包分析</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 菜鸟程序员博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>